config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  root "snippets#index"
  get '/search', to: 'snippets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snippet.rb
class Snippet < ApplicationRecord
	has_many :snippet_tags
	has_many :tags, through: :snippet_tags
end

app/models/snippet_tag.rb
class SnippetTag < ApplicationRecord
	belongs_to :snippet
	belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :snippet_tags
	has_many :snippets, through: :snippet_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  # GET /snippets
  # GET /snippets.json
  def index
    if params["tags"]
      params["tags"].each do |tag|
        tag_object = Tag.find_by(name: tag)
        @snippets = !@snippets ? tag_object.snippets.reverse : tag_object.snippets.where(id: @snippets.map(&:id).reverse )
      end
    else
      @snippets = Snippet.all.reverse
    end
    @snippet = Snippet.new
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)
    respond_to do |format|
      if @snippet.save
        params["tags"].each do |tag|
          SnippetTag.create(tag_id: Tag.find_by(name: tag).id, snippet_id: @snippet.id)     
        end
        format.html { redirect_to root_path, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:name, :url, :description, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
	%head
	%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
	%title Purr Code Pen
	= csrf_meta_tags
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
	= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
	%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css", :rel => "stylesheet"}/
	%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"}
	%body
		%header.navbar.navbar-expand.navbar-dark.flex-column.flex-md-row.bd-navbar
			.navbar-nav-scroll
				%ul.navbar-nav.bd-navbar-nav.flex-row
					%a.nav-item{:href => "/"}
						%img{src: "http://hack.purrdigital.com/css/images/logo.png"}
			%form.form-inline.my-2.my-lg-0.search-bar{"action" => "/search"}
				%select.form-control.tag-selector{:name => "tags[]", :multiple =>"multiple", :placeholder => "Search by tags"}
					-Tag.all.each do |tag|
						%option{:value => tag.name}
							=tag.name
				%button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
		.container
			= yield

app/views/snippets/_form.html.haml
= form_with(model: snippet, local: true, :html => {:class => 'col-12'}) do |form|
  - if snippet.errors.any?
    #error_explanation
      %h2
        = pluralize(snippet.errors.count, "error")
        prohibited this snippet from being saved:
      %ul
        - snippet.errors.full_messages.each do |message|
          %li= message
  %h5 Do you have something useful you want the team to see?
  .row
    .col-6
      .field.form-group
        = form.label 'Give it a name'
        = form.text_field :name, id: :snippet_name, class: 'form-control', maxlength: 50, required: true
      .field.form-group
        = form.label 'Is there a link to a github page where youve put this into action?'
        = form.text_field :url, id: :snippet_url, class: 'form-control'
    .col-6
      .field.form-group
        = form.label 'What does this do?'
        = form.text_field :description, id: :snippet_description, class: 'form-control', maxlength: 200, required: true
      .field.form-group.tag-container
        %h5 Add some tags to make it easier to search for
        %select.form-control.tag-selector{:name => "tags[]", :multiple =>"multiple"}
          -Tag.all.each do |tag|
            %option{:value => tag.name}
              =tag.name
  .field.form-group
    = form.label 'Put your code down here sucker'
    = form.text_area :code, id: :snippet_code, class: 'form-control'
  .actions
    = form.submit class: 'btn btn-primary'

app/views/snippets/_tag_fields.html.haml
.nested-fields
	.field.form-group
		= f.label 'Add name of tag here'
		= f.text_field :name, class: 'form-control'
	= link_to_remove_association "remove tag", f

app/views/snippets/edit.html.haml
%h1 Editing Snippet
= render 'form', snippet: @snippet
= link_to 'Show', @snippet
|
= link_to 'Back', snippets_path

app/views/snippets/index.html.haml
= render 'form', snippet: @snippet
- @snippets.each_slice(2) do |snippets|
  .card-group
    -snippets.each do |snippet|
      .card.col-6
        / %img.card-img-top{:alt => "Card image cap", :src => "..."}/
        .card-body
          %h5.card-title 
            =snippet.name
          %p.card-text.description
            =snippet.description
          %p.card-text
            %small.text-muted 
              Added on #{snippet.created_at.strftime('%D')}
          .code-display
            =snippet.code.html_safe
          .tags-display
            -if snippet.tags.any?
              -snippet.tags.each do |tag|     
                %span.tag-item
                  =tag.name

app/views/snippets/new.html.haml
%h1 New Snippet
= render 'form', snippet: @snippet
= link_to 'Back', snippets_path

app/views/snippets/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @snippet.name
%p
  %strong Url:
  = @snippet.url
%p
  %strong Description:
  = @snippet.description
%p
  %strong Code:
  = @snippet.code
= link_to 'Edit', edit_snippet_path(@snippet)
|
= link_to 'Back', snippets_path